# Generated by Django 2.2.15 on 2020-08-10 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField(default=0)),
                ('task_name', models.CharField(max_length=500)),
                ('task_description', models.CharField(max_length=150)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(auto_now_add=True)),
                ('url', models.CharField(max_length=500)),
                ('task_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Task_Details',
            fields=[
                ('task_updated_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_id', models.IntegerField(default=0)),
                ('update_info', models.CharField(max_length=500)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('employee_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='task_pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_attachment_id', models.IntegerField(default=0, null=True)),
                ('mailbox_id', models.IntegerField(default=0)),
                ('subject', models.CharField(max_length=500)),
                ('message_id', models.CharField(max_length=500)),
                ('in_reply_to_id', models.IntegerField(default=0, null=True)),
                ('from_header', models.CharField(max_length=500)),
                ('to_header', models.CharField(max_length=500)),
                ('outgoing', models.BooleanField(default=False)),
                ('body', models.TextField(blank=True, null=True)),
                ('encoded', models.BooleanField(default=False)),
                ('processed', models.DateTimeField(auto_now_add=True)),
                ('read', models.DateTimeField(auto_now_add=True)),
                ('eml', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.category')),
            ],
        ),
    ]
