# Generated by Django 3.0.9 on 2020-08-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task_Details',
            fields=[
                ('task_updated_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_id', models.IntegerField(default=0)),
                ('update_info', models.CharField(max_length=500)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('employee_id', models.IntegerField(default=0)),
            ],
        ),
    ]
