# Generated by Django 2.2.15 on 2020-08-10 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task_pool',
            old_name='message_attachment_id',
            new_name='msg_attch_id',
        ),
    ]
