# Generated by Django 2.2.15 on 2020-08-07 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20200807_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_pool',
            name='mail_box',
        ),
    ]
